
target 'PYDaikuan' do
    pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
    pod 'AVOSCloudIM'             # 实时通信模块
    pod 'AVOSCloudCrashReporting' # 错误报告模块
    pod 'UMengAnalytics-NO-IDFA'
    pod 'JPush', '~> 3.0.1'
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMengUShare/UI'
    
    # 集成新浪微博
    pod 'UMengUShare/Social/Sina'
    
    # 集成微信
    pod 'UMengUShare/Social/WeChat'
    
    # 集成QQ
    pod 'UMengUShare/Social/QQ'
    
    pod 'SVProgressHUD','~>2.0.4'
    
end
